{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}


apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ $.Values.global.customer }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: 
                name: {{ .Release.Name }}-apisvc
                port:
                  number: 80
    - host: {{ $.Values.global.customer }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ .Release.Name }}-websvc
                port:
                  number: 80
