apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "napidb.fullname" . }}
  labels:
    {{- include "napidb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "napidb.selectorLabels" . | nindent 4 }}
