apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-{{ include "napidb.fullname" . }}
  labels:
    {{- include "napidb.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.size }}