apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apisvc
  labels:
    {{- include "napiapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "napiapi.selectorLabels" . | nindent 4 }}
